### ISSUE TITLE
New image tag is not considered during clusterctl upgrade

### ISSUE THREAD

**Issue by Xenwar** [Nordix/airship-dev-tools#207]
Given clusterctl.yaml, the image tag and repositroy should be considred during both `clusterctl int `and `clusterctl upgrade`.
Currently, the image tag and repository is ignored during `clusterctl upgrade`
```
cat /home/$USER/.cluster-api/clusterctl.yaml
providers:
 - name: cluster-api
   url: /home/$USER/.cluster-api/overrides/cluster-api/v0.3.1/core-components.yaml
   type: CoreProvider
 
images:
 cert-manager-controller:
   repository: quay.io/jetstack
   tag: v0.11.1
```
